### ISSUE TITLE
Missing code license

### ISSUE THREAD

**Issue by ehegnes** [Andremoniy/cypress-visual-regression-ressemble-js#14]
Hi @Andremoniy. This repository is stated as a derivative fork of https://github.com/cypress-visual-regression/cypress-visual-regression, which is licensed under the MIT License.

Please consider the following to comply with licensure and make your repository available to others.
- Choose a license for your repository (https://choosealicense.com/). It is common for derivative work to inherit the parent project license.
- Include a copy of your chosen license at the root of the repository in a `LICENSE` file.

CC: @Zaista

**Comment by Andremoniy** [comment]
Hi @ehegnes.

Thank you for this remark - we simply missed this point. The MIT license is now added: https://github.com/Andremoniy/cypress-visual-regression-resemble-js/blob/main/LICENSE
