### ISSUE TITLE
visualRegressionCopy - ENOENT

### ISSUE THREAD

**Issue by dstoyanoff** [Andremoniy/cypress-visual-regression-ressemble-js#9]
Hello,
I am experiencing a problem with the `visualRegressionCopy` task. It tries to copy from `screenshots/{specName}/{fileName}`, while the screenshots for some reason get stored in `screenshots/{fileName}`. I see that you are using `Cypress.spec.name`, which when I print I get the right spec name, but not inside this command.

Any ideas?

**Comment by Andremoniy** [comment]
@dstoyanoff  thanks for letting us know about this problem. We'll have a look.

**Comment by PpBoyington** [comment]
Hi @dstoyanoff, would you have some stack print  of the error or full project to share in order to help us investigate ?

**Comment by dstoyanoff** [comment]
Hello,
Unfortunately I don't have the option to provide a repro at the moment, but from what I recall, the error was thrown [here](https://github.com/Andremoniy/cypress-visual-regression-resemble-js/blob/main/src/plugin.js#L44).

The `from` argument was trying to copy a file with path `screenshots/{specName}/{fileName}`, while my screenshots were written in `screenshots/{fileName}`.

Not sure if that's helpful at all, but hope it is.

**Comment by AMolo1782** [comment]
I run into this issue when using cypress > 10. The newer cypress versions have a different folder scheme, support for this was added to the `cypress-visual-regression` repo with their 2.0.0 release.

**Comment by Andremoniy** [comment]
@dstoyanoff  @AMolo1782  we released a new version 1.1.0 with some fixes related to the screenshot paths. Can you please check and let us know if the problem is fixed or still persists?

**Comment by AMolo1782** [comment]
The issue is not fixed for me with 1.1.0. Still have the same issue:

```
no such file or directory, copyfile 'project-root/e2e_tests/snapshots/actual/test_folder/Test Image-base-1679927330380.png' -> 'e2e_tests/snapshots/base/test_folder/Test Image-base.png'
```

When I view the folder I see there was no file inside `project-root/e2e_tests/snapshots/actual/test_folder`, I instead see my image at `project-root/e2e_tests/snapshots/actual/Test Image-base-1679927330380.png`

**Comment by Andremoniy** [comment]
> The issue is not fixed for me with 1.1.0. Still have the same issue:
> 
> ```
> no such file or directory, copyfile 'project-root/e2e_tests/snapshots/actual/test_folder/Test Image-base-1679927330380.png' -> 'e2e_tests/snapshots/base/test_folder/Test Image-base.png'
> ```
> 
> When I view the folder I see there was no file inside `project-root/e2e_tests/snapshots/actual/test_folder`, I instead see my image at `project-root/e2e_tests/snapshots/actual/Test Image-base-1679927330380.png`

@AMolo1782  I am not sure where this `test_folder` is coming from. Can you please share your `cypress.config.ts`?

**Comment by AMolo1782** [comment]
@Andremoniy 
`test_folder` in this case is where my test is located within the `specs` folder:

```
e2e_tests
|- specs
   |- test_folder
      |- test_file.cy.js

```


Here is my config (Cypress version 12.5.1):
```
import { defineConfig } from 'cypress'

export default defineConfig({
  viewportHeight: 720,
  viewportWidth: 1280,
  trashAssetsBeforeRuns: true,
  env: {
    SNAPSHOT_BASE_DIRECTORY: 'e2e_tests/snapshots/base',
    SNAPSHOT_ACTUAL_DIRECTORY: 'e2e_tests/snapshots/actual',
    SNAPSHOT_DIFF_DIRECTORY: 'e2e_tests/snapshots/diff',
    type: 'base',
  },
  e2e: {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    setupNodeEvents: (on, config) => require('./e2e_tests/plugins')(on, config),
    specPattern: 'e2e_tests/specs/**/*.cy.{js,jsx,ts,tsx}',
    supportFile: 'e2e_tests/support/index.js',
    testIsolation: true,
  },
})

```

**Comment by PpBoyington** [comment]
> @Andremoniy `test_folder` in this case is where my test is located within the `specs` folder:
> 
> ```
> e2e_tests
> |- specs
>    |- test_folder
>       |- test_file.cy.js
> ```
> 
> Here is my config (Cypress version 12.5.1):
> 
> ```
> import { defineConfig } from 'cypress'
> 
> export default defineConfig({
>   viewportHeight: 720,
>   viewportWidth: 1280,
>   trashAssetsBeforeRuns: true,
>   env: {
>     SNAPSHOT_BASE_DIRECTORY: 'e2e_tests/snapshots/base',
>     SNAPSHOT_ACTUAL_DIRECTORY: 'e2e_tests/snapshots/actual',
>     SNAPSHOT_DIFF_DIRECTORY: 'e2e_tests/snapshots/diff',
>     type: 'base',
>   },
>   e2e: {
>     // eslint-disable-next-line @typescript-eslint/no-var-requires
>     setupNodeEvents: (on, config) => require('./e2e_tests/plugins')(on, config),
>     specPattern: 'e2e_tests/specs/**/*.cy.{js,jsx,ts,tsx}',
>     supportFile: 'e2e_tests/support/index.js',
>     testIsolation: true,
>   },
> })
> ```

I'm a bit confused, SNAPSHOT_ACTUAL_DIRECTORY does not exist as an env variable, the actual folder needs to be precised using "screenshotsFolder" as a config variable like in this file -> [cypress.config.ts)](https://github.com/Andremoniy/cypress-visual-regression-resemble-js/blob/main/docker/sample_application/sample_application_cypress/cypress.config.ts)
Could you try to use "screenshotsFolder" ?

**Comment by AMolo1782** [comment]
Using the config from above I get the same copy errors:

```
import { defineConfig } from 'cypress'

export default defineConfig({
  viewportHeight: 720,
  viewportWidth: 1280,
  trashAssetsBeforeRuns: true,
  screenshotsFolder: 'e2e_tests/snapshots/actual',
  env: {
    type: 'base',
  },
  e2e: {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    setupNodeEvents: (on, config) => require('./e2e_tests/plugins')(on, config),
    specPattern: 'e2e_tests/specs/**/*.cy.{js,jsx,ts,tsx}',
    supportFile: 'e2e_tests/support/index.js',
    testIsolation: true,
  },
})
```

**Comment by PpBoyington** [comment]
> Using the config from above I get the same copy errors:
> 
> ```
> import { defineConfig } from 'cypress'
> 
> export default defineConfig({
>   viewportHeight: 720,
>   viewportWidth: 1280,
>   trashAssetsBeforeRuns: true,
>   screenshotsFolder: 'e2e_tests/snapshots/actual',
>   env: {
>     type: 'base',
>   },
>   e2e: {
>     // eslint-disable-next-line @typescript-eslint/no-var-requires
>     setupNodeEvents: (on, config) => require('./e2e_tests/plugins')(on, config),
>     specPattern: 'e2e_tests/specs/**/*.cy.{js,jsx,ts,tsx}',
>     supportFile: 'e2e_tests/support/index.js',
>     testIsolation: true,
>   },
> })
> ```

wait, why have you removed SNAPSHOT_BASE_DIRECTORY and SNAPSHOT_DIFF_DIRECTORY ? Could you please try again after adding back this in the config:
env: {
    SNAPSHOT_BASE_DIRECTORY: 'e2e_tests/snapshots/base',
    SNAPSHOT_DIFF_DIRECTORY: 'e2e_tests/snapshots/diff',
  },

**Comment by AMolo1782** [comment]
@Andremoniy I have done that and the issue still exists.

**Comment by Andremoniy** [comment]
@AMolo1782  can you provide us with a branch/pull request/repository that reproduces the problem?

**Comment by Andremoniy** [comment]
@dstoyanoff  was your original problem fixed? Can you confirm please?

**Comment by libid0nes** [comment]
same thing
```
cy.task('visualRegressionCopy') failed with the following error:



> ENOENT: no such file or directory, copyfile '\cypress\e2e\files\snapshots\actual\BookFileViewer.cy.ts\BookFileViewer-base-1712833151844.png' -> '\cypress\snapshots\base\BookFileViewer.cy.ts\BookFileViewer-base.png'
```
cypress.config.ts
```
export default defineConfig({
  viewportWidth: 1920,
  viewportHeight: 1080,

  component: {
    setupNodeEvents(on, config) {
      config.env = envLocal;
      return config;
    },
    devServer: {
      framework: "create-react-app",
      bundler: "webpack",
    },
  },
  watchForFileChanges: true,
  env: {
    video: false,
    failSilently: false,
    CYPRESS_E2E_URL: process.env.CYPRESS_E2E_URL,
    CYPRESS_E2E_AUTH_LOGIN: process.env.CYPRESS_E2E_AUTH_LOGIN,
    CYPRESS_E2E_AUTH_PASSWORD: process.env.CYPRESS_E2E_AUTH_PASSWORD
  },
  e2e: {
    screenshotsFolder: './cypress/e2e/files/snapshots/actual',
    baseUrl: process.env.CYPRESS_E2E_URL,
    setupNodeEvents(on, config) {
      getCompareSnapshotsPlugin(on, config),

      on('task', {
        async 'zfs:reset'() {
          const { data } = await axios.get(`${process.env.CYPRESS_E2E_RESET_DB_URL}/reset`)
          return data
        },
        async 'zfs:resetSnapshots'() {
          const { data } = await axios.get(`${process.env.CYPRESS_E2E_RESET_DB_URL}/resetSnapshots`)
          return data
        },
        async 'zfs:setAuthSnapshot'() {
          const { data } = await axios.get(`${process.env.CYPRESS_E2E_RESET_DB_URL}/setAuthSnapshot`)
          return data
        },
      })
    },
  },
});

```
